server:
  port: 8081

ollama:
  base-url: http://127.0.0.1:11434
  model-name: llama3.1

logging:
  level:
    dev.langchain4j: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:./data/promptarchitect
    driver-class-name: org.h2.Driver
    username: Aravind
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false